name: Cypress CI/CD

on:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SAUCECTL_VERSION: "0.175.0"
  BUILD_PREFIX: true

jobs:
  cypress:
    name: Cypress with Sauce Labs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Set saucectl Env variables from github secrets
        run: |
          sed -i "s|XXXSAUCE_USERNAMEXXX|${{secrets.SAUCE_USERNAME}}|g" ".env_cypress"
          sed -i "s|XXXSAUCE_ACCESS_KEYXXX|${{secrets.SAUCE_ACCESS_KEY}}|g" ".env_cypress"
          cat ".env_cypress"

      - name: Install Dependencies
        run: npm install

      - name: Execute SauceCTL Tests
        run: npm run saucectl-run
