name: Cypress CI/CD

on:
  push:
    branches:
      - main

jobs:
  cypress:
    name: Cypress with Sauce Labs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Set up Sauce Labs credentials
        run: |
          sed -i "s|XXXSAUCE_USERNAMEXXX|${{secrets.SAUCE_USERNAME}}|g" ".env_cypress"
          sed -i "s|XXXSAUCE_ACCESS_KEYXXX|${{secrets.SAUCE_ACCESS_KEY}}|g" ".env_cypress"
          cat ".env_cypress"
      - name: Install Dependencies
        run: npm install
      - name: Cypress with Typescript
        uses: saucelabs/saucectl-run-action@v3
      - name: Run Cypress tests
        env:
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
        run: |
          npm run cy:run -- --env sauceUsername=$SAUCE_USERNAME --env sauceAccessKey=$SAUCE_ACCESS_KEY
