name: Cypress CI/CD

on:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  cypress:
    name: Cypress with Sauce Labs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "14"
      - name: Install Dependencies
        run: npm install
      - name: Cypress with Typescript
        uses: saucelabs/saucectl-run-action@v3
      - name: Cypress Run
        run: |
          npm run saucectl
